### ISSUE TITLE
Colors Not Accurate in Dark Mode

### ISSUE THREAD

**Issue by MCDELTAT** [nautobot/nautobot-app-floor-plan#61]
### Environment
* Python version:  Unknown. Demo sandbox, not specified in nautobot-lab container image.
* Nautobot version:  2.0.5
* nautobot-floor-plan version:  2.0.0

### Observed Behavior
On the Nautobot demo deployment, in dark mode, colors on the floor plan page do not always match the original Organization –> Statuses object.

### Expected Behavior
The Floor Plan page should display the same color as selected in the Organization –> Statuses object.

I began by following the introduction to the Floor Plan Plugin here: https://blog.networktocode.com/post/nautobot-floor-plan-app/

### Steps to Reproduce
1. Create two new Statuses under Organization –> Statuses. Names can be anything, Colors should be Yellow and Amber.
2. Add a tile object to a Location Floor Plan using the new statuses.
3. Export the SVG of the Floorplan.
4. Compare the colors in the live, Dark Mode view and the exported SVG. They will be different.

Two images included to show the difference:
Light Mode:
![Screen Shot 2023-12-11 at 7 33 49 PM](https://github.com/nautobot/nautobot-plugin-floor-plan/assets/6556275/cecea36b-dea5-49d3-b19f-6b4fb1d6921e)

Dark Mode:
![Screen Shot 2023-12-11 at 7 34 22 PM](https://github.com/nautobot/nautobot-plugin-floor-plan/assets/6556275/5ccad193-fabb-430d-8d71-910a72148be7)

**Comment by djhoward12** [comment]
Confirmed this issue. 

When in dark mode `filter: invert(1) hue-rotate(180deg);` needs to be added to .tile-status, l.abel-text and .label-text-primary

```css
.tile-status {
    stroke: black;
    fill: #f7f7f7;
    opacity: .6;
    filter: invert(1) hue-rotate(180deg);
}

.label-text {
    fill: white;
    filter: invert(1) hue-rotate(180deg);
}
.label-text-primary {
    fill: white;
    font-weight: bold;
    filter: invert(1) hue-rotate(180deg);
}
```

A custom css file is being loaded on line 70 in svg.py

**Comment by djhoward12** [comment]
I was able to get this mostly working using the below code in svg.css.

```css
.tile-status {
    stroke: black;
    fill: #f7f7f7;
    opacity: .6;

}

@media (prefers-color-scheme:dark) {
    .tile-status {
        stroke: black;
        fill: #f7f7f7;
        opacity: .6;
        filter: invert(1) hue-rotate(180deg);
    }
}
```

This works fine if the the system theme setting is used in Nautobot. If the browser setting is dark and the user selects light mode manually, the prefers-color-scheme still defaults to dark in the css. 

![dark](https://github.com/nautobot/nautobot-app-floor-plan/assets/45186384/46db6663-4b76-4e6e-81c5-8a2e956fefd6)
![light](https://github.com/nautobot/nautobot-app-floor-plan/assets/45186384/c0daa764-09e9-4289-b47e-54ca635089a6)
